// ============================================================
// build-demo.mjs
// Generates demo.html from index.html so the two never drift.
//
//   node build-demo.mjs
//
// demo.html is the same app as index.html, but with window.DD_DEMO = true set
// before the deferred scripts run. That flag makes:
//   - backend.js  → disable ALL telemetry + never record a result (DEMO guard)
//   - script.js   → skip /today and launch a RANDOM practice district via the
//                   `demo` Edge Function, through the unofficial archive-replay path.
// Re-run this whenever index.html changes.
// ============================================================
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const DIR = dirname(fileURLToPath(import.meta.url));
let html = readFileSync(join(DIR, 'index.html'), 'utf8');

// Guard: while the pre-launch teaser is live, index.html is NOT the game — regenerating
// demo.html from it would produce a broken demo. Restore the game index.html first.
if (html.includes('TEMPORARY pre-launch teaser')) {
  process.stderr.write('index.html is the pre-launch teaser, not the game — restore the game index.html before regenerating demo.html. Aborting.\n');
  process.exit(1);
}

// 1. Flag + noindex, injected right after <head> so the classic inline script runs
//    before the deferred backend.js/script.js execute.
const headInject =
  `\n  <script>window.DD_DEMO = true;</script>` +
  `\n  <meta name="robots" content="noindex" />`;
html = html.replace(/<head>/, `<head>${headInject}`);

// 2. Title.
html = html.replace(/<title>[\s\S]*?<\/title>/, '<title>Daily District — Demo (practice mode)</title>');

// 3. Body gets a `demo` class (drives the demo chrome CSS below).
html = html.replace(/<body(\s[^>]*)?>/, (m, attrs = '') => {
  if (/class=/.test(attrs || '')) return m.replace(/class="([^"]*)"/, 'class="$1 demo"');
  return `<body${attrs || ''} class="demo">`;
});

// 4. Demo chrome: a fixed "practice mode" bar with a New-district button, plus CSS that
//    hides the auth UI (there's nothing to sign into in demo). Injected before </body>.
const demoChrome = `
<style>
  body.demo #demo-bar {
    position: fixed; left: 50%; transform: translateX(-50%); bottom: 14px; z-index: 4000;
    display: flex; align-items: center; gap: 10px;
    background: rgba(20,22,28,.94); color: #fff; padding: 8px 10px 8px 14px; border-radius: 999px;
    box-shadow: 0 6px 22px rgba(0,0,0,.32); font: 500 13px/1 system-ui, -apple-system, Segoe UI, Roboto, sans-serif;
  }
  body.demo #demo-bar .demo-tag {
    background: #c41230; color: #fff; padding: 3px 8px; border-radius: 999px;
    font-weight: 700; font-size: 11px; letter-spacing: .09em;
  }
  body.demo #demo-bar .demo-text { color: #cdd0d6; }
  body.demo #demo-new-btn {
    background: #c41230; color: #fff; border: 0; padding: 7px 13px; border-radius: 999px;
    font: 600 13px system-ui, sans-serif; cursor: pointer;
  }
  body.demo #demo-new-btn:hover { filter: brightness(1.08); }
  body.demo #demo-new-btn:focus-visible { outline: 2px solid #fff; outline-offset: 2px; }
  /* No auth in demo — nothing is recorded. */
  body.demo #header-signin-btn, body.demo .account-wrap, body.demo #welcome-signin-btn { display: none !important; }
  @media (max-width: 540px) { body.demo #demo-bar .demo-text { display: none; } }
</style>
<div id="demo-bar" role="status">
  <span class="demo-tag">DEMO</span>
  <span class="demo-text">Practice mode — nothing is saved</span>
  <button type="button" id="demo-new-btn">🎲 New district</button>
</div>
<script>
  document.getElementById('demo-new-btn')?.addEventListener('click', function () {
    if (window.startDemoGame) window.startDemoGame();
  });
</script>
`;
html = html.replace(/<\/body>/, `${demoChrome}</body>`);

// Banner so no one hand-edits the generated file.
html = html.replace(/^<!DOCTYPE html>/i,
  `<!DOCTYPE html>\n<!-- GENERATED by build-demo.mjs from index.html — do not edit by hand. -->`);

writeFileSync(join(DIR, 'demo.html'), html);
process.stderr.write('Wrote demo.html\n');
