#!/usr/bin/env python3
"""
apply_compactness.py — turn compactness_out.csv (from compactness.R) into SQL that
writes the shape metrics into puzzles.census.

Stores the COMPONENT PARTS (area_sqmi, perimeter_mi) — the client needs them to draw
the District Area card + the Polsby-Popper figure — plus reock. Polsby-Popper itself is
derived on the client from area + perimeter, so it isn't stored. Percentile ranks
(census.pct.compactness / .reock) are still computed afterwards by derived_update.sql,
which reads these census values (no geometry needed).

Replaces the old PostGIS perimeter/reock bake.

Usage:  python3 apply_compactness.py   ->  compactness_update.sql   (then: make push-compactness)
"""
import csv, os

HERE = os.path.dirname(__file__)
SRC  = os.path.join(HERE, "compactness_out.csv")
DST  = os.path.join(HERE, "compactness_update.sql")

def main():
    rows = []
    with open(SRC) as f:
        for r in csv.DictReader(f):
            rows.append((r["district_id"], int(r["area_sqmi"]), int(r["perimeter_mi"]), float(r["reock"])))
    rows.sort()
    vals = ",\n  ".join(f"('{d}',{a},{p},{k})" for d, a, p, k in rows)
    sql = ("-- Generated by apply_compactness.py (from compactness.R) — district shape metrics.\n"
           "UPDATE puzzles p SET census = census || jsonb_build_object(\n"
           "  'area_sqmi', n.area_sqmi, 'perimeter_mi', n.perimeter_mi, 'reock', n.reock)\n"
           "FROM (VALUES\n  " + vals + "\n) AS n(district_id, area_sqmi, perimeter_mi, reock)\n"
           "WHERE p.district_id = n.district_id;\n")
    open(DST, "w").write(sql)
    print(f"{len(rows)} districts -> {DST}  ({len(sql)} bytes)")

if __name__ == "__main__":
    main()
