#!/usr/bin/env python3
"""
apply_census.py — turn census_out.json into idempotent SQL that updates
puzzles.census for every district.

The ACS fields are replaced wholesale; the four NON-ACS fields already in the
stored census are preserved untouched:
    area_sqmi        (computed from the 2026 polygon, not ACS)
    Margin2024Pres   2024 presidential margin
    DemPct2024Pres   2024 Democratic share
    RepPct2024Pres   2024 Republican share

Output: census_update.sql  (run via psql / Supabase SQL editor / apply_migration)

Usage
  python3 build_census.py            # -> census_out.json
  python3 apply_census.py            # -> census_update.sql
"""
import json, os

HERE=os.path.dirname(__file__)
SRC=os.environ.get("DD_CENSUS_OUT", os.path.join(HERE,"census_out.json"))
DST=os.path.join(HERE,"census_update.sql")
PRESERVE=["area_sqmi","perimeter_mi","reock","pop2020","Margin2024Pres","DemPct2024Pres","RepPct2024Pres","rep","pct"]

def sqllit(obj):
    return "'" + json.dumps(obj,separators=(',',':')).replace("'","''") + "'"

def main():
    data=json.load(open(SRC))
    preserve_obj="jsonb_build_object(" + ",".join(f"'{k}',p.census->'{k}'" for k in PRESERVE) + ")"
    rows=[f"('{did}',{sqllit(data[did])}::jsonb)" for did in sorted(data)]
    sql=("-- Generated by apply_census.py — rebuild puzzles.census from ACS tract aggregation.\n"
         "-- ACS fields replaced; area_sqmi + 2024-presidential fields preserved from existing census.\n"
         "UPDATE puzzles p SET census = " + preserve_obj + " || n.acs\n"
         "FROM (VALUES\n  " + ",\n  ".join(rows) + "\n) AS n(district_id, acs)\n"
         "WHERE p.district_id = n.district_id;\n")
    open(DST,"w").write(sql)
    print(f"{len(data)} districts -> {DST}  ({len(sql)} bytes)")

if __name__=="__main__":
    main()
