#!/usr/bin/env python3
"""
build_reps.py — current U.S. House member for each district.

Source: the official directory at https://www.house.gov/representatives, which
the Clerk of the House keeps current. We scrape its per-state tables and write a
`rep` object onto each district's puzzles.census:

    { "name": "Dina Titus", "party": "Democratic", "partyCode": "D",
      "url": "https://titus.house.gov/" }

Representatives change over time — re-run this whenever House membership shifts.
It only touches census->'rep'; the demographic fields are untouched (and
apply_census.py preserves 'rep' so a census rebuild won't drop it). Vacant seats
are skipped (no rep written).

Outputs reps_out.json + reps_update.sql. Apply the SQL like the census one.
"""
import json, os, re, html, urllib.request

URL = "https://www.house.gov/representatives"
HERE = os.path.dirname(__file__)
OUT_JSON = os.path.join(HERE, "reps_out.json")
OUT_SQL  = os.path.join(HERE, "reps_update.sql")
ABBR = {'alabama':'AL','alaska':'AK','arizona':'AZ','arkansas':'AR','california':'CA','colorado':'CO','connecticut':'CT','delaware':'DE','florida':'FL','georgia':'GA','hawaii':'HI','idaho':'ID','illinois':'IL','indiana':'IN','iowa':'IA','kansas':'KS','kentucky':'KY','louisiana':'LA','maine':'ME','maryland':'MD','massachusetts':'MA','michigan':'MI','minnesota':'MN','mississippi':'MS','missouri':'MO','montana':'MT','nebraska':'NE','nevada':'NV','new hampshire':'NH','new jersey':'NJ','new mexico':'NM','new york':'NY','north carolina':'NC','north dakota':'ND','ohio':'OH','oklahoma':'OK','oregon':'OR','pennsylvania':'PA','rhode island':'RI','south carolina':'SC','south dakota':'SD','tennessee':'TN','texas':'TX','utah':'UT','vermont':'VT','virginia':'VA','washington':'WA','west virginia':'WV','wisconsin':'WI','wyoming':'WY'}
# house.gov's Party column is a single letter (D/R/I); expand to a full label.
PARTY_LABEL = {'D':'Democrat','R':'Republican','I':'Independent','L':'Libertarian'}

def clean(s):
    return html.unescape(re.sub(r'\s+', ' ', s)).strip()

def sqllit(obj):
    return "'" + json.dumps(obj, separators=(',',':')).replace("'","''") + "'"

def main():
    req = urllib.request.Request(URL, headers={'User-Agent':'Mozilla/5.0'})
    with urllib.request.urlopen(req, timeout=60) as r:
        page = r.read().decode('utf-8', 'replace')
    # Each state is a <table> whose <caption> holds the state name. Split on captions.
    parts = re.split(r'<caption[^>]*>\s*([^<]+?)\s*</caption>', page)
    reps = {}
    # parts = [pre, stateName1, body1, stateName2, body2, ...]
    for i in range(1, len(parts) - 1, 2):
        st = ABBR.get(clean(parts[i]).lower())
        if not st:
            continue
        body = parts[i + 1]
        for tr in re.findall(r'<tr>(.*?)</tr>', body, re.S):
            dm = re.search(r'views-field-value-2[^>]*>(.*?)</td>', tr, re.S)
            nm = re.search(r'views-field-value-4[^>]*>(.*?)</td>', tr, re.S)
            pm = re.search(r'views-field-value-7[^>]*>(.*?)</td>', tr, re.S)
            if not (dm and nm and pm):
                continue
            dtxt = clean(re.sub(r'<[^>]+>', '', dm.group(1)))
            num = 1 if dtxt.lower().startswith('at') else int(re.match(r'(\d+)', dtxt).group(1)) if re.match(r'(\d+)', dtxt) else None
            if num is None:
                continue
            a = re.search(r'<a href="([^"]+)"[^>]*>(.*?)</a>', nm.group(1), re.S)
            if not a:
                continue  # vacant seat (no link)
            last_first = clean(re.sub(r'<[^>]+>', '', a.group(2)))
            if ',' in last_first:
                last, first = [p.strip() for p in last_first.split(',', 1)]
                name = f"{first} {last}".strip()
            else:
                name = last_first
            raw_party = clean(re.sub(r'<[^>]+>', '', pm.group(1)))
            code = (raw_party[:1] or '?').upper()
            url = clean(a.group(1))
            # house.gov occasionally links a sitting member to a clerk "vacancy"
            # placeholder rather than their site — drop that so the card has no bad link.
            if 'clerk.house.gov' in url or '/vacancy' in url:
                url = ''
            reps[f"{st}-{num:02d}"] = {
                "name": name,
                "party": PARTY_LABEL.get(code, raw_party),
                "partyCode": code,
                "url": url,
            }
    json.dump(reps, open(OUT_JSON, "w"))
    rows = [f"('{did}',{sqllit(reps[did])}::jsonb)" for did in sorted(reps)]
    sql = ("-- Generated by build_reps.py — set census->'rep' (current U.S. House member).\n"
           "-- Source: https://www.house.gov/representatives\n"
           "UPDATE puzzles p SET census = coalesce(p.census,'{}'::jsonb) || jsonb_build_object('rep', n.rep)\n"
           "FROM (VALUES\n  " + ",\n  ".join(rows) + "\n) AS n(district_id, rep)\n"
           "WHERE p.district_id = n.district_id;\n")
    open(OUT_SQL, "w").write(sql)
    print(f"{len(reps)} reps -> {OUT_JSON} + {OUT_SQL}  ({len(sql)} bytes)")

if __name__ == "__main__":
    main()
