#!/usr/bin/env python3
"""
build_pop2020.py — 2020 Census population per 2026 district, for the "change since
2020" figure on the District Profile.

Aggregates the 2020 Decennial (PL 94-171) total population (table P1_001N) at the
TRACT level up to each 2026 district using the SAME crosswalk as build_census.py —
so the 2020 count and the ACS count are apples-to-apples (any difference is real
population change, not a geography mismatch). Outputs pop2020_update.sql, which sets
census.pop2020; the client shows (ACS pop − pop2020)/pop2020 as the % change.

Usage:  python3 build_pop2020.py   ->  pop2020_update.sql   (then: make push-pop2020)
"""
import json, os, urllib.request, urllib.parse
from collections import defaultdict
import build_census as bc   # reuse FIPS, ATLARGE, tract_crosswalk

DEC = "https://api.census.gov/data/2020/dec/pl"
OUT = os.path.join(os.path.dirname(__file__), "pop2020_update.sql")

def fetch_tract_pop(fips):
    q = urllib.parse.urlencode({"get": "P1_001N", "for": "tract:*", "in": f"state:{fips} county:*", "key": bc.KEY})
    with urllib.request.urlopen(f"{DEC}?{q}", timeout=180) as r:
        rows = json.loads(r.read())
    h = rows[0]; gi = (h.index("state"), h.index("county"), h.index("tract")); pi = h.index("P1_001N")
    out = {}
    for row in rows[1:]:
        try: out[row[gi[0]] + row[gi[1]] + row[gi[2]]] = int(row[pi])
        except: pass
    return out

def main():
    res = {}
    for st in sorted(bc.FIPS):
        tracts = fetch_tract_pop(bc.FIPS[st])
        xwalk = bc.tract_crosswalk(st)            # tract(11) -> district; None for at-large
        # CT-style GEOID-vintage repair (same as build_census): remap crosswalk tracts
        # to the data's GEOIDs by 6-digit tract number when the direct join misses.
        if xwalk is not None:
            have = set(tracts)
            by_t6 = defaultdict(list)
            for g in have: by_t6[g[5:]].append(g)
            for g in [g for g in xwalk if g not in have]:
                cand = by_t6.get(g[5:])
                if cand and len(cand) == 1: xwalk[cand[0]] = xwalk[g]
        for g, pop in tracts.items():
            dist = '01' if st in bc.ATLARGE else (xwalk or {}).get(g)
            if dist is None: continue
            did = f"{st}-{int(dist):02d}"
            res[did] = res.get(did, 0) + pop
        print(f"{st}: {sum(1 for k in res if k[:2]==st)} districts", flush=True)
    rows = [f"('{did}',{res[did]})" for did in sorted(res)]
    sql = ("-- Generated by build_pop2020.py — 2020 Census population per 2026 district.\n"
           "UPDATE puzzles p SET census = census || jsonb_build_object('pop2020', n.pop2020)\n"
           "FROM (VALUES\n  " + ",\n  ".join(rows) + "\n) AS n(district_id, pop2020)\n"
           "WHERE p.district_id = n.district_id;\n")
    open(OUT, "w").write(sql)
    print(f"\n{len(res)} districts -> {OUT}")

if __name__ == "__main__":
    main()
