#!/usr/bin/env python3
"""
build_plan_year.py — "district plan last redrawn" year per state, for the District
Profile.

The current national map is assembled by taking the most recent plan per state from the
DRA block-assignment folder (files named like "LA 2024 Congressional.csv"). The latest
filename's year for a state IS the year that state's congressional map was last redrawn —
the same files build_census.py aggregates. (The districts-core.topojson `year` field is
missing for a few states, e.g. LA, so we read it straight from the filenames instead.)

Plan year is per STATE (a whole state redraws together), so the SQL updates by state.

Usage:  python3 build_plan_year.py   ->  plan_year_update.sql   (then: make push-plan-year)
"""
import os, re
import build_census as bc   # reuse BAF_DIR + FIPS

OUT = os.path.join(os.path.dirname(__file__), "plan_year_update.sql")
PAT = re.compile(r"^([A-Z]{2}) (\d{4}) Congressional\.csv$")

def main():
    years = {}   # state -> latest plan year
    for f in os.listdir(bc.BAF_DIR):
        m = PAT.match(f)
        if not m:
            continue
        st, yr = m.group(1), int(m.group(2))
        if st in bc.FIPS and yr > years.get(st, 0):
            years[st] = yr
    rows = ",\n  ".join(f"('{st}',{yr})" for st, yr in sorted(years.items()))
    sql = ("-- Generated by build_plan_year.py — latest congressional plan year per state\n"
           "-- (from the DRA block-assignment filenames = the map currently in effect).\n"
           "UPDATE puzzles p SET census = census || jsonb_build_object('planYear', n.yr)\n"
           "FROM (VALUES\n  " + rows + "\n) AS n(state, yr)\n"
           "WHERE p.state = n.state;\n")
    open(OUT, "w").write(sql)
    print(f"{len(years)} states -> {OUT}")

if __name__ == "__main__":
    main()
