#!/usr/bin/env python3
"""
build_lang.py — person-level "speaks a language other than English at home" per
2026 district, for the District Profile.

The full census build now uses the person-level table C16001 (population 5+) for
nonEnglishPct; this is a targeted recompute that updates ONLY census.nonEnglishPct
in the live DB (so we don't have to re-run the whole census just to fix one field).
Aggregates C16001 at the TRACT level with the same crosswalk as build_census.py.

  C16001_001E = population 5 years and over
  C16001_002E = speak only English
  nonEnglishPct = 100 * (001 - 002) / 001  (share of all residents 5+, not households)

Usage:  python3 build_lang.py   ->  lang_update.sql   (then: make push-lang)
"""
import json, os, urllib.request, urllib.parse
from collections import defaultdict
import build_census as bc   # reuse FIPS, ATLARGE, tract_crosswalk, KEY

OUT = os.path.join(os.path.dirname(__file__), "lang_update.sql")

def fetch_tract(fips):
    q = urllib.parse.urlencode({"get": "C16001_001E,C16001_002E", "for": "tract:*",
                                "in": f"state:{fips} county:*", "key": bc.KEY})
    with urllib.request.urlopen(f"{bc.ACS}?{q}", timeout=180) as r:
        rows = json.loads(r.read())
    h = rows[0]; gi = (h.index("state"), h.index("county"), h.index("tract"))
    ti, ei = h.index("C16001_001E"), h.index("C16001_002E")
    out = {}
    for row in rows[1:]:
        try: out[row[gi[0]] + row[gi[1]] + row[gi[2]]] = (int(row[ti]), int(row[ei]))
        except: pass
    return out

def main():
    agg = defaultdict(lambda: [0, 0])   # district -> [total, english_only]
    for st in sorted(bc.FIPS):
        tracts = fetch_tract(bc.FIPS[st])
        xwalk = bc.tract_crosswalk(st)
        if xwalk is not None:                 # CT-style GEOID-vintage repair
            have = set(tracts); by_t6 = defaultdict(list)
            for g in have: by_t6[g[5:]].append(g)
            for g in [g for g in xwalk if g not in have]:
                cand = by_t6.get(g[5:])
                if cand and len(cand) == 1: xwalk[cand[0]] = xwalk[g]
        for g, (tot, eng) in tracts.items():
            dist = '01' if st in bc.ATLARGE else (xwalk or {}).get(g)
            if dist is None: continue
            did = f"{st}-{int(dist):02d}"
            agg[did][0] += tot; agg[did][1] += eng
        print(f"{st}: {sum(1 for k in agg if k[:2]==st)} districts", flush=True)
    res = {did: round((tot - eng) / tot * 100, 1) for did, (tot, eng) in agg.items() if tot}
    rows = [f"('{did}',{res[did]})" for did in sorted(res)]
    sql = ("-- Generated by build_lang.py — person-level non-English (C16001) per 2026 district.\n"
           "UPDATE puzzles p SET census = census || jsonb_build_object('nonEnglishPct', n.v)\n"
           "FROM (VALUES\n  " + ",\n  ".join(rows) + "\n) AS n(district_id, v)\n"
           "WHERE p.district_id = n.district_id;\n")
    open(OUT, "w").write(sql)
    print(f"\n{len(res)} districts -> {OUT}")

if __name__ == "__main__":
    main()
