#!/usr/bin/env Rscript
# apply_drivetime.R — turn drivetime_out.csv (from drivetime.R) into SQL that writes the
# drive-time fields into puzzles.census.
#
# The stat is "max drive time WITHOUT LEAVING THE DISTRICT" — the routing graph is clipped
# to the district polygon, so it measures internal road connectivity. See drivetime.R.
#
# Fields written:
#   max_drive_min        road-only minutes (ferries excluded). NULL when no sampled pair is
#                        connected by road — a genuine finding about the district, so the
#                        client must handle null rather than assume a number.
#   max_drive_from/to    [lon,lat] endpoints of that road-only max, for a map overlay.
#   max_drive_route_mi   road miles for that route, and
#   max_drive_route      its encoded polyline (precision 5) so a map can draw the real path.
#
#   span_drive_min       minutes between the two most spread-out road-connected points —
#                        "cross it end to end", as opposed to max_drive_min's "worst pair
#                        anywhere". A district can be slow without being big (VA-03, water
#                        crossings: max/span = 1.41) or big without being slow (VA-09,
#                        rural: 1.00). Neither number alone distinguishes those.
#   span_mi              straight-line miles for that pair; span_route_mi the road miles.
#                        Their ratio is the detour factor (VA-08 Arlington 1.53 vs VA-06 1.13).
#   span_from/to, span_route   endpoints and encoded polyline for the same pair.
#   geo_diameter_mi      widest straight-line separation among sampled points, ignoring
#                        reachability — the district's raw geometric span.
#   max_drive_min_ferry  ferry-inclusive minutes. Equal to max_drive_min for the ~majority
#                        of districts; diverges only where ferries matter (MA-09, AK-01).
#                        OSRM's synthetic ferry duration — no schedule wait — so indicative.
#   max_drive_ferry_from/to  endpoints of the ferry-inclusive max.
#   max_drive_connected  TRUE when every sampled point is mutually reachable by road.
#   max_drive_component  largest mutually-reachable group / points sampled, as a fraction —
#                        <1 means the district's road network splits into pieces.
#   max_drive_points     how many sampled points actually survived to the calculation.
#                        Not decoration: points far offshore or in roadless country are
#                        dropped, so a district like CA-11 (whose second polygon part is the
#                        Farallon Islands, 40 km out) is computed from 9 points, not 24.
#                        A low count means thin coverage — treat the figure as coarser.
#
# The UPDATE only touches district_ids present in the CSV, so a partial (single-state) run
# is safe to push without disturbing every other district's census row.
#
# Usage:  Rscript apply_drivetime.R [in.csv]   ->  drivetime_update.sql
#         (then: make push-drivetime)

HERE <- tryCatch(dirname(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE))), error = function(e) ".")
source(file.path(HERE, "config.R"))

args <- commandArgs(trailingOnly = TRUE)
SRC  <- if (length(args) >= 1) args[[1]] else file.path(HERE, "drivetime_out.csv")
DST  <- file.path(HERE, "drivetime_update.sql")

df <- read.csv(SRC, stringsAsFactors = FALSE)
df <- df[order(df$district_id), ]

# NA -> SQL NULL, so a road-disconnected district stores null rather than a bogus number.
num <- function(x) ifelse(is.na(x), "NULL", format(x, trim = TRUE, scientific = FALSE))
# Polylines are text; NA must still become NULL, not the string 'NA'.
txt <- function(x) ifelse(is.na(x), "NULL", sql_literal(x))
connected <- ifelse(df$unreachable_pairs == 0, "true", "false")
component <- round(df$largest_component / df$n_points, 3)

vals <- sprintf("('%s',%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)",
                df$district_id,
                num(df$max_drive_min), num(df$from_lon), num(df$from_lat),
                num(df$to_lon), num(df$to_lat),
                num(df$max_drive_min_ferry),
                num(df$ferry_from_lon), num(df$ferry_from_lat),
                num(df$ferry_to_lon), num(df$ferry_to_lat),
                connected, num(component), num(df$n_points),
                num(df$max_route_mi), txt(df$max_route_poly),
                num(df$span_drive_min), num(df$span_mi), num(df$span_route_mi),
                num(df$span_from_lon), num(df$span_from_lat),
                num(df$span_to_lon), num(df$span_to_lat),
                txt(df$span_route_poly))

sql <- paste0(
  "-- Generated by apply_drivetime.R (from drivetime.R).\n",
  "-- \"Max drive time without leaving the district\": the OSRM graph is clipped to the\n",
  "-- district polygon, so this measures internal road connectivity, not absolute distance.\n",
  "-- max_drive_min is NULL where no sampled pair is road-connected (islands, severed halves);\n",
  "-- max_drive_min_ferry covers those cases but is OSRM's synthetic ferry duration.\n",
  "UPDATE puzzles p SET census = census || jsonb_build_object(\n",
  "  'max_drive_min', n.max_drive_min,\n",
  "  'max_drive_from', jsonb_build_array(n.from_lon, n.from_lat),\n",
  "  'max_drive_to', jsonb_build_array(n.to_lon, n.to_lat),\n",
  "  'max_drive_min_ferry', n.max_drive_min_ferry,\n",
  "  'max_drive_ferry_from', jsonb_build_array(n.ferry_from_lon, n.ferry_from_lat),\n",
  "  'max_drive_ferry_to', jsonb_build_array(n.ferry_to_lon, n.ferry_to_lat),\n",
  "  'max_drive_connected', n.connected,\n",
  "  'max_drive_component', n.component,\n",
  "  'max_drive_points', n.points,\n",
  "  'max_drive_route_mi', n.max_route_mi,\n",
  "  'max_drive_route', n.max_route_poly,\n",
  "  'span_drive_min', n.span_drive_min,\n",
  "  'span_mi', n.span_mi,\n",
  "  'span_route_mi', n.span_route_mi,\n",
  "  'span_from', jsonb_build_array(n.span_from_lon, n.span_from_lat),\n",
  "  'span_to', jsonb_build_array(n.span_to_lon, n.span_to_lat),\n",
  "  'span_route', n.span_route_poly)\n",
  "FROM (VALUES\n  ", paste(vals, collapse = ",\n  "), "\n",
  ") AS n(district_id, max_drive_min, from_lon, from_lat, to_lon, to_lat,\n",
  "       max_drive_min_ferry, ferry_from_lon, ferry_from_lat, ferry_to_lon, ferry_to_lat,\n",
  "       connected, component, points, max_route_mi, max_route_poly,\n",
  "       span_drive_min, span_mi, span_route_mi,\n",
  "       span_from_lon, span_from_lat, span_to_lon, span_to_lat, span_route_poly)\n",
  "WHERE p.district_id = n.district_id;\n"
)
write_sql(DST, sql, nrow(df), "districts")
