#!/usr/bin/env Rscript
# apply_compactness.R — turn compactness_out.csv (from compactness.R) into SQL that
# writes the shape metrics into puzzles.census.
#
# Stores the COMPONENT PARTS (area_sqmi, perimeter_mi) — the client needs them to draw
# the District Area card + the Polsby-Popper figure — plus reock. Polsby-Popper itself
# is derived on the client from area + perimeter, so it isn't stored (compactness.R's
# own polsby_popper/adj columns feed districts.topojson directly, not this SQL).
#
# Usage:  Rscript apply_compactness.R   ->  compactness_update.sql   (then: make push-compactness)

HERE <- tryCatch(dirname(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE))), error = function(e) ".")
source(file.path(HERE, "config.R"))

SRC <- file.path(HERE, "compactness_out.csv")
DST <- file.path(HERE, "compactness_update.sql")

df <- read.csv(SRC, stringsAsFactors = FALSE)
df <- df[order(df$district_id), ]
vals <- sprintf("('%s',%d,%d,%s)", df$district_id, as.integer(df$area_sqmi), as.integer(df$perimeter_mi), df$reock)

sql <- paste0(
  "-- Generated by apply_compactness.R (from compactness.R) — district shape metrics.\n",
  "UPDATE puzzles p SET census = census || jsonb_build_object(\n",
  "  'area_sqmi', n.area_sqmi, 'perimeter_mi', n.perimeter_mi, 'reock', n.reock)\n",
  "FROM (VALUES\n  ", paste(vals, collapse = ",\n  "), "\n) AS n(district_id, area_sqmi, perimeter_mi, reock)\n",
  "WHERE p.district_id = n.district_id;\n"
)
write_sql(DST, sql, nrow(df), "districts")
