#!/usr/bin/env Rscript
# apply_census.R — turn census_out.json into idempotent SQL that updates
# puzzles.census for every district.
#
# The ACS fields are replaced wholesale; the non-ACS fields already in the stored
# census are preserved untouched: area_sqmi, perimeter_mi, reock, pop2020, planYear,
# Margin2024Pres, DemPct2024Pres, RepPct2024Pres, rep, pct.
#
# Output: census_update.sql  (run via psql / Supabase SQL editor / apply_migration)
#
# Usage
#   Rscript census.R          # -> census_out.json
#   Rscript apply_census.R    # -> census_update.sql

HERE <- tryCatch(dirname(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE))), error = function(e) ".")
source(file.path(HERE, "config.R"))

SRC <- file.path(HERE, "census_out.json")
DST <- file.path(HERE, "census_update.sql")
PRESERVE <- c("area_sqmi", "perimeter_mi", "reock", "pop2020", "planYear",
              "Margin2024Pres", "DemPct2024Pres", "RepPct2024Pres", "rep", "pct")

data <- jsonlite::fromJSON(SRC, simplifyVector = FALSE)
preserve_obj <- paste0("jsonb_build_object(",
                       paste(sprintf("'%s',p.census->'%s'", PRESERVE, PRESERVE), collapse = ","), ")")

dids <- sort(names(data))
rows <- vapply(dids, function(did) sprintf("('%s',%s)", did, jsonb_literal(data[[did]])), character(1))

sql <- paste0(
  "-- Generated by apply_census.R — rebuild puzzles.census from ACS tract aggregation.\n",
  "-- ACS fields replaced; area_sqmi + 2024-presidential fields preserved from existing census.\n",
  "UPDATE puzzles p SET census = ", preserve_obj, " || n.acs\n",
  "FROM (VALUES\n  ", paste(rows, collapse = ",\n  "), "\n) AS n(district_id, acs)\n",
  "WHERE p.district_id = n.district_id;\n"
)
write_sql(DST, sql, length(dids), "districts")
