#!/usr/bin/env Rscript
# lang.R — person-level "speaks a language other than English at home" per 2026
# district, for the District Profile.
#
# The full census.R build uses the person-level table C16001 (population 5+) for
# nonEnglishPct; this is a targeted recompute that updates ONLY census.nonEnglishPct
# in the live DB (so we don't have to re-run the whole census just to fix one field).
# Aggregates C16001 at the TRACT level with the same crosswalk as census.R.
#
#   C16001_001E = population 5 years and over
#   C16001_002E = speak only English
#   nonEnglishPct = 100 * (001 - 002) / 001  (share of all residents 5+, not households)
#
# Usage:  Rscript lang.R   ->  lang_update.sql   (then: make push-lang)

HERE <- tryCatch(dirname(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE))), error = function(e) ".")
source(file.path(HERE, "config.R"))

OUT <- file.path(HERE, "lang_update.sql")
states <- sort(setdiff(names(FIPS), c("DC", "PR")))

agg_tot <- list(); agg_eng <- list()
for (st in states) {
  tracts <- fetch_acs_tract(st, c("C16001_001E", "C16001_002E"), year = ACS_YEAR_CENSUS)
  xwalk <- tract_crosswalk_plurality(st)
  if (!is.null(xwalk)) xwalk <- ct_geoid_repair(xwalk, tracts$GEOID)
  dist <- if (st %in% AT_LARGE) rep("01", nrow(tracts)) else unname(xwalk[tracts$GEOID])

  valid <- !is.na(dist)
  dids <- sprintf("%s-%02d", st, as.integer(dist[valid]))
  tot_agg <- tapply(tracts$C16001_001E[valid], dids, sum, na.rm = TRUE)
  eng_agg <- tapply(tracts$C16001_002E[valid], dids, sum, na.rm = TRUE)
  for (d in names(tot_agg)) {
    agg_tot[[d]] <- (if (is.null(agg_tot[[d]])) 0 else agg_tot[[d]]) + tot_agg[[d]]
    agg_eng[[d]] <- (if (is.null(agg_eng[[d]])) 0 else agg_eng[[d]]) + eng_agg[[d]]
  }
  message(sprintf("%s: %d districts", st, length(tot_agg)))
}

dids <- sort(names(agg_tot))
res <- setNames(vapply(dids, function(d) {
  tot <- agg_tot[[d]]; eng <- agg_eng[[d]]
  if (tot > 0) round((tot - eng) / tot * 100, 1) else NA_real_
}, numeric(1)), dids)
res <- res[!is.na(res)]
dids <- names(res)

rows <- sprintf("('%s',%s)", dids, unname(res))
sql <- paste0(
  "-- Generated by lang.R — person-level non-English (C16001) per 2026 district.\n",
  "UPDATE puzzles p SET census = census || jsonb_build_object('nonEnglishPct', n.v)\n",
  "FROM (VALUES\n  ", paste(rows, collapse = ",\n  "), "\n) AS n(district_id, v)\n",
  "WHERE p.district_id = n.district_id;\n"
)
write_sql(OUT, sql, length(dids), "districts")
