#!/usr/bin/env Rscript
# plan_year.R — "district plan last redrawn" year per state, for the District
# Profile.
#
# The current national map is assembled by taking the most recent plan per state from
# the DRA block-assignment folder (files named like "LA 2024 Congressional.csv"). The
# latest filename's year for a state IS the year that state's congressional map was
# last redrawn — the same files census.R aggregates. Plan year is per STATE (a whole
# state redraws together), so the SQL updates by state.
#
# Usage:  Rscript plan_year.R   ->  plan_year_update.sql   (then: make push-plan-year)

HERE <- tryCatch(dirname(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE))), error = function(e) ".")
source(file.path(HERE, "config.R"))

OUT <- file.path(HERE, "plan_year_update.sql")
cd_states <- setdiff(names(FIPS), c("DC", "PR"))

files <- list.files(BAF_DIR)
m <- regmatches(files, regexec("^([A-Z]{2}) ([0-9]{4}) Congressional\\.csv$", files))

years <- list()
for (mm in m) {
  if (length(mm) == 0) next
  st <- mm[2]; yr <- as.integer(mm[3])
  if (st %in% cd_states && (is.null(years[[st]]) || yr > years[[st]])) years[[st]] <- yr
}

states <- sort(names(years))
rows <- vapply(states, function(st) sprintf("('%s',%d)", st, years[[st]]), character(1))

sql <- paste0(
  "-- Generated by plan_year.R — latest congressional plan year per state\n",
  "-- (from the DRA block-assignment filenames = the map currently in effect).\n",
  "UPDATE puzzles p SET census = census || jsonb_build_object('planYear', n.yr)\n",
  "FROM (VALUES\n  ", paste(rows, collapse = ",\n  "), "\n) AS n(state, yr)\n",
  "WHERE p.state = n.state;\n"
)
write_sql(OUT, sql, length(states), "states")
