#!/usr/bin/env Rscript
# pop2020.R — 2020 Census population per 2026 district, for the "change since
# 2020" figure on the District Profile.
#
# Aggregates the 2020 Decennial (PL 94-171) total population (table P1_001N) at the
# TRACT level up to each 2026 district using the SAME crosswalk as census.R — so the
# 2020 count and the ACS count are apples-to-apples (any difference is real
# population change, not a geography mismatch). Outputs pop2020_update.sql, which sets
# census.pop2020; the client shows (ACS pop - pop2020)/pop2020 as the % change.
#
# Usage:  Rscript pop2020.R   ->  pop2020_update.sql   (then: make push-pop2020)

HERE <- tryCatch(dirname(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE))), error = function(e) ".")
source(file.path(HERE, "config.R"))

OUT <- file.path(HERE, "pop2020_update.sql")
states <- sort(setdiff(names(FIPS), c("DC", "PR")))

res <- list()
for (st in states) {
  tracts <- fetch_decennial_tract(st, "P1_001N")
  xwalk <- tract_crosswalk_plurality(st)
  if (!is.null(xwalk)) xwalk <- ct_geoid_repair(xwalk, tracts$GEOID)
  dist <- if (st %in% AT_LARGE) rep("01", nrow(tracts)) else unname(xwalk[tracts$GEOID])

  valid <- !is.na(dist)
  dids <- sprintf("%s-%02d", st, as.integer(dist[valid]))
  agg <- tapply(tracts$P1_001N[valid], dids, sum, na.rm = TRUE)
  for (d in names(agg)) res[[d]] <- (if (is.null(res[[d]])) 0 else res[[d]]) + agg[[d]]
  message(sprintf("%s: %d districts", st, length(agg)))
}

dids <- sort(names(res))
rows <- sprintf("('%s',%d)", dids, unlist(res[dids]))
sql <- paste0(
  "-- Generated by pop2020.R — 2020 Census population per 2026 district.\n",
  "UPDATE puzzles p SET census = census || jsonb_build_object('pop2020', n.pop2020)\n",
  "FROM (VALUES\n  ", paste(rows, collapse = ",\n  "), "\n) AS n(district_id, pop2020)\n",
  "WHERE p.district_id = n.district_id;\n"
)
write_sql(OUT, sql, length(dids), "districts")
