#!/usr/bin/env Rscript
# reps.R — current U.S. House member for each district.
#
# Source: the official directory at https://www.house.gov/representatives, which
# the Clerk of the House keeps current. We scrape its per-state tables and write a
# `rep` object onto each district's puzzles.census:
#
#     { "name": "Dina Titus", "party": "Democratic", "partyCode": "D",
#       "url": "https://titus.house.gov/" }
#
# Representatives change over time — re-run this whenever House membership shifts.
# It only touches census->'rep'; the demographic fields are untouched (and
# apply_census.R preserves 'rep' so a census rebuild won't drop it). Vacant seats
# are skipped (no rep written).
#
# Outputs reps_out.json + reps_update.sql. Apply the SQL like the census one.

HERE <- tryCatch(dirname(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE))), error = function(e) ".")
source(file.path(HERE, "config.R"))
suppressMessages(library(rvest))

URL <- "https://www.house.gov/representatives"
OUT_JSON <- file.path(HERE, "reps_out.json")
OUT_SQL  <- file.path(HERE, "reps_update.sql")

ABBR <- c(alabama="AL", alaska="AK", arizona="AZ", arkansas="AR", california="CA", colorado="CO",
          connecticut="CT", delaware="DE", florida="FL", georgia="GA", hawaii="HI", idaho="ID",
          illinois="IL", indiana="IN", iowa="IA", kansas="KS", kentucky="KY", louisiana="LA",
          maine="ME", maryland="MD", massachusetts="MA", michigan="MI", minnesota="MN",
          mississippi="MS", missouri="MO", montana="MT", nebraska="NE", nevada="NV",
          "new hampshire"="NH", "new jersey"="NJ", "new mexico"="NM", "new york"="NY",
          "north carolina"="NC", "north dakota"="ND", ohio="OH", oklahoma="OK", oregon="OR",
          pennsylvania="PA", "rhode island"="RI", "south carolina"="SC", "south dakota"="SD",
          tennessee="TN", texas="TX", utah="UT", vermont="VT", virginia="VA", washington="WA",
          "west virginia"="WV", wisconsin="WI", wyoming="WY")
# house.gov's Party column is a single letter (D/R/I); expand to a full label.
PARTY_LABEL <- c(D = "Democrat", R = "Republican", I = "Independent", L = "Libertarian")

page <- read_html(URL)
tables <- html_elements(page, "table")

reps <- list()
for (tbl in tables) {
  caption <- html_element(tbl, "caption")
  if (inherits(caption, "xml_missing")) next
  st <- unname(ABBR[tolower(trimws(html_text2(caption)))])
  if (is.na(st)) next

  for (tr in html_elements(tbl, "tr")) {
    dnode <- html_element(tr, ".views-field-value-2")
    nnode <- html_element(tr, ".views-field-value-4")
    pnode <- html_element(tr, ".views-field-value-7")
    if (inherits(dnode, "xml_missing") || inherits(nnode, "xml_missing") || inherits(pnode, "xml_missing")) next

    dtxt <- trimws(html_text2(dnode))
    num <- if (grepl("^at", dtxt, ignore.case = TRUE)) {
      1L
    } else {
      mm <- regmatches(dtxt, regexpr("[0-9]+", dtxt))
      if (length(mm) && nzchar(mm)) as.integer(mm) else NA_integer_
    }
    if (is.na(num)) next

    a <- html_element(nnode, "a")
    if (inherits(a, "xml_missing")) next   # vacant seat (no link)
    last_first <- trimws(html_text2(a))
    if (grepl(",", last_first, fixed = TRUE)) {
      parts <- strsplit(last_first, ",", fixed = TRUE)[[1]]
      name <- trimws(paste(trimws(parts[2]), trimws(parts[1])))
    } else {
      name <- last_first
    }

    raw_party <- trimws(html_text2(pnode))
    code <- toupper(substr(if (nzchar(raw_party)) raw_party else "?", 1, 1))
    url <- trimws(html_attr(a, "href"))
    # house.gov occasionally links a sitting member to a clerk "vacancy"
    # placeholder rather than their site — drop that so the card has no bad link.
    if (grepl("clerk.house.gov", url, fixed = TRUE) || grepl("/vacancy", url, fixed = TRUE)) url <- ""

    did <- sprintf("%s-%02d", st, num)
    reps[[did]] <- list(
      name = name,
      party = if (code %in% names(PARTY_LABEL)) unname(PARTY_LABEL[code]) else raw_party,
      partyCode = code,
      url = url
    )
  }
}

jsonlite::write_json(reps, OUT_JSON, auto_unbox = TRUE, null = "null", na = "null", digits = NA)

dids <- sort(names(reps))
rows <- sprintf("('%s',%s)", dids, vapply(dids, function(d) jsonb_literal(reps[[d]]), character(1)))
sql <- paste0(
  "-- Generated by reps.R — set census->'rep' (current U.S. House member).\n",
  "-- Source: https://www.house.gov/representatives\n",
  "UPDATE puzzles p SET census = coalesce(p.census,'{}'::jsonb) || jsonb_build_object('rep', n.rep)\n",
  "FROM (VALUES\n  ", paste(rows, collapse = ",\n  "), "\n) AS n(district_id, rep)\n",
  "WHERE p.district_id = n.district_id;\n"
)
write_sql(OUT_SQL, sql, length(dids), "reps")
