// ============================================================
// build-mica.mjs
// Generates mica.html from index.html so the two never drift.
//
//   node scripts/build-mica.mjs
//
// mica.html is the same app as index.html, but with window.DD_ONEOFF = true set
// before the deferred scripts run. That flag makes script.js skip /today and launch
// the FIXED "special edition" district from the `oneoff` endpoint instead (see
// startOneoffGame() in script.js) — every player gets the same district. Unlike
// demo.html, this mode DOES record a result (win/loss/guesses/seconds) once per
// identity, and keeps the real sign-in UI visible: a player can play anonymously or
// sign in first/mid-game, same as the daily. Re-run this whenever index.html changes.
// ============================================================
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const DIR = join(dirname(fileURLToPath(import.meta.url)), '..'); // repo root (script lives in scripts/)
let html = readFileSync(join(DIR, 'index.html'), 'utf8');

// Guard: while the pre-launch teaser is live, index.html is NOT the game — regenerating
// mica.html from it would produce a broken page. Restore the game index.html first
// (see LAUNCH.md: `git checkout launch-index -- index.html`).
if (html.includes('TEMPORARY pre-launch teaser')) {
  process.stderr.write('index.html is the pre-launch teaser, not the game — restore the game index.html before regenerating mica.html. Aborting.\n');
  process.exit(1);
}

// 1. Flag + noindex, injected right after <head> so the classic inline script runs
//    before the deferred backend.js/script.js execute.
const headInject =
  `\n  <script>window.DD_ONEOFF = true;</script>` +
  `\n  <meta name="robots" content="noindex" />`;
html = html.replace(/<head>/, `<head>${headInject}`);

// 2. Title.
html = html.replace(/<title>[\s\S]*?<\/title>/, '<title>Daily District — Special Edition</title>');

// 3. Body gets a `oneoff` class (drives the chrome CSS below).
html = html.replace(/<body(\s[^>]*)?>/, (m, attrs = '') => {
  if (/class=/.test(attrs || '')) return m.replace(/class="([^"]*)"/, 'class="$1 oneoff"');
  return `<body${attrs || ''} class="oneoff">`;
});

// 4. No fixed bottom bar here (unlike demo.html's demo-bar): a fixed overlay at this
//    position covers the bottom row of the state-chip list on common viewport heights
//    (verified — document.elementFromPoint() on a chip's coordinates hit the bar
//    instead), and unlike demo's bar it has no button to justify the tradeoff. The
//    in-game archive-badge (set from the event's own title once loaded, same element
//    demo/archive already use) is enough context — no extra chrome needed. Unlike
//    demo.html's chrome, this also does NOT hide the sign-in UI — playing signed in or
//    anonymous is the whole point.

// Banner so no one hand-edits the generated file.
html = html.replace(/^<!DOCTYPE html>/i,
  `<!DOCTYPE html>\n<!-- GENERATED by build-mica.mjs from index.html — do not edit by hand. -->`);

writeFileSync(join(DIR, 'mica.html'), html);
process.stderr.write('Wrote mica.html\n');
